#!/usr/bin/env bash
# dsh-desktop local installer: builds deps and registers a launcher + desktop
# entry + icon under the user's ~/.local tree. No system-wide writes.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAUNCHER_NAME="dsh-desktop"
APP_NAME="DeepSeek Harness"
BIN_DIR="${HOME}/.local/bin"
APPS_DIR="${HOME}/.local/share/applications"
ICON_ROOT="${HOME}/.local/share/icons/hicolor"
PIXMAPS_DIR="${HOME}/.local/share/pixmaps"
ICON_NAME="dsh-desktop"
ICON_PNG="${ICON_ROOT}/512x512/apps/${ICON_NAME}.png"

echo "==> dsh-desktop installer"
echo "    project: ${PROJECT_DIR}"

# 1. Node is required to run the harness host (spawned under system Node).
if ! NODE_BIN="$(command -v node)"; then
  echo "error: 'node' not found on PATH — the dsh host needs it" >&2
  exit 1
fi
echo "    node:    ${NODE_BIN}"

# 2. Install dependencies (pnpm preferred, npm fallback).
if command -v pnpm >/dev/null 2>&1; then
  PM=pnpm
else
  PM=npm
fi
echo "    install: ${PM} install (this downloads Electron and @deepseek-ai/dsh)"
( cd "$PROJECT_DIR" && "$PM" install )

# 3. Icon at every standard size (theme lookup), plus a pixmaps copy and a
#    512px canonical file the desktop entry points at by absolute path.
SIZES="16 22 24 32 48 64 96 128 256 512"
if [ -f "$PROJECT_DIR/assets/icon.svg" ] && command -v rsvg-convert >/dev/null 2>&1; then
  for s in $SIZES; do
    mkdir -p "${ICON_ROOT}/${s}x${s}/apps"
    rsvg-convert -w "$s" -h "$s" "$PROJECT_DIR/assets/icon.svg" -o "${ICON_ROOT}/${s}x${s}/apps/${ICON_NAME}.png"
  done
  echo "    icons:   rendered at ${SIZES} from svg"
else
  for s in $SIZES; do
    mkdir -p "${ICON_ROOT}/${s}x${s}/apps"
    if [ "$s" = "512" ] && [ -f "$PROJECT_DIR/assets/icon.png" ]; then
      cp "$PROJECT_DIR/assets/icon.png" "${ICON_ROOT}/512x512/apps/${ICON_NAME}.png"
    elif command -v magick >/dev/null 2>&1; then
      magick "$PROJECT_DIR/assets/icon.png" -resize "${s}x${s}" "${ICON_ROOT}/${s}x${s}/apps/${ICON_NAME}.png"
    fi
  done
  echo "    icons:   installed from bundled png"
fi
mkdir -p "$PIXMAPS_DIR"
cp "$ICON_PNG" "${PIXMAPS_DIR}/${ICON_NAME}.png"

# 4. Launcher script. DSH_NODE is baked so the shell works even when launched
#    from a minimal .desktop session whose PATH lacks node.
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/${LAUNCHER_NAME}" <<EOF
#!/usr/bin/env bash
# Generated by dsh-desktop install.sh — re-run install.sh to update.
export DSH_NODE="${NODE_BIN}"
exec "${PROJECT_DIR}/node_modules/.bin/electron" "${PROJECT_DIR}" "\$@"
EOF
chmod +x "$BIN_DIR/${LAUNCHER_NAME}"
echo "    launcher: ${BIN_DIR}/${LAUNCHER_NAME}"

# 5. `dsh` CLI — the same harness version the desktop app runs, so plugin
#    management (`dsh plugin --profile web add <pkg>`) targets the right tree.
cat > "$BIN_DIR/dsh" <<EOF
#!/usr/bin/env bash
# Generated by dsh-desktop install.sh — re-run install.sh to update.
export DSH_NODE="${NODE_BIN}"
exec "${NODE_BIN}" "${PROJECT_DIR}/node_modules/@deepseek-ai/dsh/lib/bin.js" "\$@"
EOF
chmod +x "$BIN_DIR/dsh"
echo "    dsh CLI:  ${BIN_DIR}/dsh"

# 6. Desktop entry. Icon points at the canonical PNG by absolute path so
#    dmenu-style launchers (fuzzel/rofi/wofi) resolve it without the theme cache.
mkdir -p "$APPS_DIR"
cat > "$APPS_DIR/${LAUNCHER_NAME}.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=${APP_NAME}
Comment=AI coding agent harness
Exec=${BIN_DIR}/${LAUNCHER_NAME}
Icon=${ICON_PNG}
Terminal=false
Categories=Development;Utility;
StartupWMClass=${APP_NAME}
EOF
echo "    desktop:  ${APPS_DIR}/${LAUNCHER_NAME}.desktop"

# 7. Refresh icon/desktop caches (best effort).
command -v update-desktop-database >/dev/null 2>&1 \
  && update-desktop-database "${APPS_DIR}" >/dev/null 2>&1 || true
command -v gtk-update-icon-cache >/dev/null 2>&1 \
  && gtk-update-icon-cache -f "${ICON_ROOT}" >/dev/null 2>&1 || true

echo
echo "==> Done. Launch with: ${BIN_DIR}/${LAUNCHER_NAME}"
case ":${PATH}:" in
  *":${BIN_DIR}:"*) ;;
  *) echo "    note: ${BIN_DIR} is not on your PATH; add it or launch by full path." ;;
esac
